M48
; DRILL file {KiCad 8.0.4} date 2025-03-21T12:56:27-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-21T12:56:27-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X77.325Y-57.575
T2
X88.51Y-54.554
T3
X52.347Y-29.4
X52.347Y-101.4
X124.347Y-29.4
X124.347Y-101.4
M30
