M48
; DRILL file {KiCad 7.0.1} date Sat Mar 23 22:37:24 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-23T22:37:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X88.66Y-54.504
T2
X52.347Y-29.4
X52.347Y-101.4
X124.347Y-29.4
X124.347Y-101.4
T0
M30
