M48
; DRILL file {KiCad 8.0.4} date 2025-03-20T14:51:35-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-20T14:51:35-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.400
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X85.2Y-65.55
T2
X124.37Y-57.95
T3
X44.45Y-38.1
X44.45Y-84.1
X140.45Y-38.1
X140.45Y-84.1
M30
