M48
; DRILL file {KiCad 8.0.4} date 2025-02-21T00:53:03-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-21T00:53:03-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X81.745Y-67.409
X124.37Y-57.95
T2
X44.45Y-38.1
X44.45Y-84.1
X140.45Y-38.1
X140.45Y-84.1
M30
