M48
; DRILL file {KiCad 7.0.7} date Sat Mar 23 22:08:50 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-23T22:08:50-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X124.358Y-58.016
T2
X44.45Y-38.1
X44.45Y-84.1
X140.45Y-38.1
X140.45Y-84.1
T0
M30
